### PR TITLE
Fix Spanish translations

### PR DESCRIPTION
**Pull request by atd**
I kept the order in `date-time` folder. I guess it matters?

I also changed the sentences for using words instead of adjectives, as I saw in `dialog/condition`. However, they will sound weird if using adjectives (which can be found in `vocabulary/condition`)

### CODE REVIEW

**Comment by emphasize** [comment]
please also translate https://github.com/atd/skill-ovos-weather/blob/staging/translation_es-es/locale/es-es/regex/location.rx
regex is too nasty to autotranslate

**Comment by emphasize** [comment]
> I kept the order in `date-time` folder. I guess it matters?

what do you mean by that?

However, i think you have to review [number-days.voc](https://github.com/OpenVoiceOS/skill-ovos-weather/pull/41/files#diff-699695097bd35b987b0fcc1865281d081cab740996ae7046677e80600974ff21) again. This is the part of the intent that signifies the span of the weather report
like en_us
```
2 day
two day
next 2 days
next two days
next couple of days
next couple days
```
autotranslate got them mixed up, so its harder to see the pattern.

rerlative-day = one day report relative from now
relative-time = report for the time of day (Lingua franca defines them [here](https://github.com/OpenVoiceOS/ovos-lingua-franca/blob/0c4ead9b3ad396fc68a5b5c6465678b567c6c01f/lingua_franca/lang/parse_es.py#L724))

**Comment by atd** [comment]
> please also translate https://github.com/atd/skill-ovos-weather/blob/staging/translation_es-es/locale/es-es/regex/location.rx

done. But I am not totally sure of the order. May I have an example of a phrase to match?

> However, i think you have to review [number-days.voc](https://github.com/OpenVoiceOS/skill-ovos-weather/pull/41/files#diff-699695097bd35b987b0fcc1865281d081cab740996ae7046677e80600974ff21) again. This is the part of the intent that signifies the span of the weather report

Yes, that is what I was asking about. I fixed the order because I saw them pretty ordered in the original

I don't understand "2 day" though. Is it 2nd day? Why day is in singular?

`next couple of days` etc... I think they are fine

**Comment by emphasize** [comment]
Sorry, had a little detour to test location intents. 

`2 day` is just a short for the the next two days

**Comment by atd** [comment]
Updated!

I cannot say it will perfect, but maybe with use I will be able to tune it

**Pull request merged**
